# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireBaseTest' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    
    # Pods for LooFinder
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'Firebase/Crash'
    pod 'Firebase/Auth'
    
end
